package view;

import javax.swing.JFrame;

import controller.cadastros.ControllerCadFornecedor;
import controller.cadastros.ControllerCadFuncionario;
import controller.cadastros.ControllerCadHospede;
import controller.cadastros.ControllerCadMarca;
import controller.cadastros.ControllerCadModelo;
import controller.cadastros.ControllerCadProdutoCopa;
import controller.cadastros.ControllerCadQuarto;
import controller.cadastros.ControllerCadServico;
import controller.cadastros.ControllerCadVagaEstacionamento;
import controller.cadastros.ControllerCadVeiculo;
import controller.cadastros.ControllerLeiame;



public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemHospedes = new javax.swing.JMenuItem();
        jMenuItemFuncionarios = new javax.swing.JMenuItem();
        jMenuItemFornecedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVeiculos = new javax.swing.JMenuItem();
        jMenuItemModelos = new javax.swing.JMenuItem();
        jMenuItemMarcas = new javax.swing.JMenuItem();
        jMenuItemVagas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuartos = new javax.swing.JMenuItem();
        jMenuItemServicos = new javax.swing.JMenuItem();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemLeiame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCadastros.setText("Cadastros");

        jMenuItemHospedes.setText("Hóspedes");
        jMenuItemHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHospedesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemHospedes);

        jMenuItemFuncionarios.setText("Funcionários");
        jMenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFuncionarios);

        jMenuItemFornecedores.setText("Fornecedores");
        jMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoresActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFornecedores);
        jMenuCadastros.add(jSeparator1);

        jMenuItemVeiculos.setText("Veículos");
        jMenuItemVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeiculosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemVeiculos);

        jMenuItemModelos.setText("Modelos");
        jMenuItemModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModelosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemModelos);

        jMenuItemMarcas.setText("Marcas");
        jMenuItemMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemMarcas);

        jMenuItemVagas.setText("Vagas");
        jMenuItemVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVagasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemVagas);
        jMenuCadastros.add(jSeparator2);

        jMenuItemQuartos.setText("Quartos");
        jMenuItemQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuartosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemQuartos);

        jMenuItemServicos.setText("Serviços");
        jMenuItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemServicos);

        jMenuItemProdutos.setText("Produtos");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemProdutos);

        jMenuBar1.add(jMenuCadastros);

        jMenuAjuda.setText("Ajuda");

        jMenuItemLeiame.setText("Leia-me");
        jMenuItemLeiame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLeiameActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemLeiame);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHospedesActionPerformed
        TelaCadHospede telaCadHospede = new TelaCadHospede(null,true);
        ControllerCadHospede controllerCadHospede = new ControllerCadHospede(telaCadHospede);
        telaCadHospede.setVisible(true);
    }//GEN-LAST:event_jMenuItemHospedesActionPerformed

    private void jMenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionariosActionPerformed
        TelaCadFuncionario telaCadFuncionario = new TelaCadFuncionario(null,true);
        ControllerCadFuncionario controllerCadFuncionario = new ControllerCadFuncionario(telaCadFuncionario);
        telaCadFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionariosActionPerformed

    private void jMenuItemVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculosActionPerformed
        TelaCadVeiculo telaCadVeiculo = new TelaCadVeiculo(null,true);
        ControllerCadVeiculo controllerCadVeiculo = new ControllerCadVeiculo(telaCadVeiculo);
        telaCadVeiculo.setVisible(true);
    }//GEN-LAST:event_jMenuItemVeiculosActionPerformed

    private void jMenuItemMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcasActionPerformed
        TelaCadMarca telaCadMarca = new TelaCadMarca(null,true);
        ControllerCadMarca controllerCadMarca = new ControllerCadMarca(telaCadMarca);
        telaCadMarca.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcasActionPerformed

    private void jMenuItemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicosActionPerformed
        TelaCadServico telaCadServico = new TelaCadServico(null,true);
        ControllerCadServico controllerCadServico = new ControllerCadServico(telaCadServico);
        telaCadServico.setVisible(true);
    }//GEN-LAST:event_jMenuItemServicosActionPerformed

    private void jMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoresActionPerformed
        TelaCadFornecedor telaCadFornecedor = new TelaCadFornecedor(null,true);
        ControllerCadFornecedor controllerCadFornecedor = new ControllerCadFornecedor(telaCadFornecedor);
        telaCadFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedoresActionPerformed

    private void jMenuItemModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModelosActionPerformed
        TelaCadModelo telaCadModelo = new TelaCadModelo(null,true);
        ControllerCadModelo controllerCadModelo = new ControllerCadModelo(telaCadModelo);
        telaCadModelo.setVisible(true);
    }//GEN-LAST:event_jMenuItemModelosActionPerformed

    private void jMenuItemVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVagasActionPerformed
        TelaCadVagaEstacionamento telaCadVagaEstacionamento = new TelaCadVagaEstacionamento(null,true);
        ControllerCadVagaEstacionamento controllerCadVagaEstacionamento = new ControllerCadVagaEstacionamento(telaCadVagaEstacionamento);
        telaCadVagaEstacionamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemVagasActionPerformed

    private void jMenuItemQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartosActionPerformed
        TelaCadQuarto telaCadQuarto = new TelaCadQuarto(null,true);
        ControllerCadQuarto controllerCadQuarto = new ControllerCadQuarto(telaCadQuarto);
        telaCadQuarto.setVisible(true);
    }//GEN-LAST:event_jMenuItemQuartosActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
        TelaCadProdutoCopa telaCadProdutoCopa = new TelaCadProdutoCopa(null,true);
        ControllerCadProdutoCopa controllerCadProdutoCopa = new ControllerCadProdutoCopa(telaCadProdutoCopa);
        telaCadProdutoCopa.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jMenuItemLeiameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLeiameActionPerformed
        TelaLeiame telaLeiame = new TelaLeiame(null,true);
        ControllerLeiame controllerLeiame = new ControllerLeiame(telaLeiame);
        telaLeiame.setVisible(true);
    }//GEN-LAST:event_jMenuItemLeiameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemFornecedores;
    private javax.swing.JMenuItem jMenuItemFuncionarios;
    private javax.swing.JMenuItem jMenuItemHospedes;
    private javax.swing.JMenuItem jMenuItemLeiame;
    private javax.swing.JMenuItem jMenuItemMarcas;
    private javax.swing.JMenuItem jMenuItemModelos;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemQuartos;
    private javax.swing.JMenuItem jMenuItemServicos;
    private javax.swing.JMenuItem jMenuItemVagas;
    private javax.swing.JMenuItem jMenuItemVeiculos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
